[homelab]
onyx ansible_host=192.168.0.2 ansible_user=rav host_ip=192.168.0.2 domain_name=onyx
ruby ansible_host=192.168.0.3 ansible_user=rav host_ip=192.168.0.3 domain_name=ruby

[homelab:vars]
ansible_ssh_private_key_file=/root/.ssh/id_home_lab
public_key=/root/.ssh/id_home_lab.pub
