---
- name: Install Proxmox
  hosts: all
  become: yes
  tasks:

    - name: Update and upgrade all packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
        state: present

    - name: Add entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "127.0.0.1      {{ domain_name }}"
        - "{{ host_ip }}  {{ domain_name }}"

    - name: Download and store Proxmox GPG key
      shell: curl -L https://mirrors.apqa.cn/proxmox/debian/pveport.gpg | tee /usr/share/keyrings/pveport.gpg >/dev/null

    - name: Add Proxmox repository
      shell: echo "deb [arch=arm64 signed-by=/usr/share/keyrings/pveport.gpg] https://mirrors.apqa.cn/proxmox/debian/pve bookworm port" | tee /etc/apt/sources.list.d/pveport.list

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Remove ifupdown2 temporary lock file if exists
      file:
        path: /tmp/.ifupdown2-first-install
        state: absent

    - name: Install ifupdown2
      apt:
        name: ifupdown2
        state: present

    - name: Configure network interfaces
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback
          
          auto eth0
          iface eth0 inet manual
          
          auto vmbr0
          iface vmbr0 inet manual
              address {{ host_ip }}
              gateway 192.168.0.1
              netmask 255.255.255.0
              bridge-ports eth0
              bridge-stp off
              bridge-fd 0

    - name: Reboot the system
      reboot:
        reboot_timeout: 180

    - name: Install Proxmox packages
      apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
          - pve-edk2-firmware-aarch64
        state: present

    - name: Done
      debug:
        msg: "Proxmox UI dostępne na http://{{ domain_name }}.local:8005 lub http://{{ host_ip }}:8006"