---
- name: Configure Keepalived failover
  hosts: homelab
  become: true
  become_flags: -n
  vars:
    virtual_ip: "192.168.0.150"
    virtual_router_id: 50
    interface: "vmbr0"
    master_host: "Onyx"
    priority_master: 150
    priority_backup: 100
  tasks:
    - name: Install Keepalived
      apt:
        name: keepalived
        state: present

    - name: Configure Keepalived
      copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
              state {% if inventory_hostname == master_host %}MASTER{% else %}BACKUP{% endif %}
    
              interface {{ interface }}
              virtual_router_id {{ virtual_router_id }}
              priority {% if inventory_hostname == master_host %}{{ priority_master }}{% else %}{{ priority_backup }}{% endif %}
          
              advert_int 1
    
              authentication {
                  auth_type PASS
                  auth_pass mysecurepass
              }
    
              virtual_ipaddress {
                  {{ virtual_ip }}/24
              }
          }
        mode: "0644"

    - name: Enable and restart Keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
